FROM python:3.9-slim

ARG TYPE
ENV TYPE=$TYPE

ARG PROJECT_ID
ENV PROJECT_ID=$PROJECT_ID

ARG PRIVATE_KEY_ID
ENV PRIVATE_KEY_ID=$PRIVATE_KEY_ID

ARG PRIVATE_KEY
ENV PRIVATE_KEY=$PRIVATE_KEY

ARG CLIENT_EMAIL
ENV CLIENT_EMAIL=$CLIENT_EMAIL

ARG CLIENT_ID
ENV CLIENT_ID=$CLIENT_ID

ARG AUTH_URI
ENV AUTH_URI=$AUTH_URI

ARG TOKEN_URI
ENV TOKEN_URI=$TOKEN_URI

ARG AUTH_PROVIDER_X509_CERT_URL
ENV AUTH_PROVIDER_X509_CERT_URL=$AUTH_PROVIDER_X509_CERT_URL

ARG CLIENT_X509_CERT_URL
ENV CLIENT_X509_CERT_URL=$CLIENT_X509_CERT_URL

ARG UNIVERSE_DOMAIN
ENV UNIVERSE_DOMAIN=$UNIVERSE_DOMAIN

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/EsraaMadi/DataScienceRoadmap.git .

RUN pip3 install -r requirements.txt


EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "🚀_Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
